name: Build and Push Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY_USER: kingsleyzissou
  IMAGE_REGISTRY: ghcr.io/kingsleyzissou

jobs:
  build:
    name: Build and push container image
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - target: fedora
            base-image: quay.io/fedora/fedora-toolbox:41
            port: 9000
          - target: centos
            base-image: quay.io/toolbx-images/centos-toolbox:stream9
            port: 9001

    steps:
    - name: Log in to ghcr.io
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.AUTH_TOKEN }}

    - name: Tag base-image
      id: tag-base
      run: |
        podman pull ${{ matrix.base-image }}
        podman tag ${{ matrix.base-image }} base-image

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: devcontainer
        tags: ${{ matrix.target }}
        containerfiles: ./Containerfile
        build-args: |
          COCKPIT_PORT=${{ matrix.port }}

    - name: Push to ghcr.io
      id: push-to-registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-registry.outputs.registry-paths }}"
