name: Build Image
on: [ pull_request ]

env:
  REGISTRY_USER: kingsleyzissou
  IMAGE_REGISTRY: ghcr.io/kingsleyzissou

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - target: fedora
            base-image: quay.io/fedora/fedora-toolbox:41
            port: 9000
          - target: centos
            base-image: quay.io/toolbx-images/centos-toolbox:stream9
            port: 9001

    steps:
    - uses: actions/checkout@v4

    - name: Tag base-image
      id: tag-base
      run: |
        podman pull ${{ matrix.base-image }}
        podman tag ${{ matrix.base-image }} base-image

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: devcontainer
        tags: ${{ matrix.target }}
        containerfiles: ./Containerfile
        build-args: |
          COCKPIT_PORT=${{ matrix.port }}
